### ISSUE TITLE
add option to save match as csv

### ISSUE THREAD

**Issue by razaqq** [razaqq/PotatoAlert#17]

**Comment by atradior** [comment]
Have an option for csv logging active / inactive
Create or append to either roaming/potatoalert/games.log or in the replay-folder games.csv
Upon getting the match data of a new match write as text
date,map,team-wr,team_damage,player_name1,ship_player1,matches_player1,winrate_player1,....damageship_player1, playername_2, [...], enemy_wr,enemy_damage,enemy_name1,enemy_ship1,.....damage_ship_enemy_last

dateformat fixed or system
not sure if names need to be escaped in ''
For players/enemies without stats probably "n/a" or none

**Comment by razaqq** [comment]
implemented in the upcoming 3.0.0 rework
