### ISSUE TITLE
Program Unable to Find App

### ISSUE THREAD

**Issue by jycmba** [razaqq/PotatoAlert#27]
Latest Aslain update install can't connect with program.

**Comment by razaqq** [comment]
you have to be more specific? what cannot connect? what is the error message? can you show me some logs?

**Comment by jycmba** [comment]
looks like I may have found where things should point..

*Loom | Free Screen & Video Recording Software - 4 December 2021* - Watch
Video <https://www.loom.com/share/56715091b38f423d9a57c081e7301362>
<https://www.loom.com/share/56715091b38f423d9a57c081e7301362?utm_medium=gif>

**Comment by razaqq** [comment]
Well yeah if you create a link you have to point it to a valid exe ofc
