### ISSUE TITLE
Operation cancelled - now not working due to this?

### ISSUE THREAD

**Issue by OohMrRigsby** [razaqq/PotatoAlert#35]

**Comment by razaqq** [comment]
provide more information like logs

**Comment by OohMrRigsby** [comment]
I start the app, it tries to run and comes up with this message. Where do I get logs from?

**Comment by razaqq** [comment]
`%localappdata%\PotatoAlert\PotatoAlert.log`

and like i said, its easier if you join the discord https://discord.com/invite/Ut8t8PA

**Comment by OohMrRigsby** [comment]
ok im there...

**Comment by razaqq** [comment]
closing this
