### ISSUE TITLE
Error Reading ArenaInfo

### ISSUE THREAD

**Issue by DarkMukke** [razaqq/PotatoAlert#36]
ever since the last update, every match I get this error
![image](https://user-images.githubusercontent.com/1083860/189536914-381713ac-9ca0-460f-9402-9ccc46a82d2b.png)

Eg I get the loading icon, and then this. If I then go to the settings, change nothing and click save, it correctly loads the info.
I'm assuming it is a race condition.

PA version : 3.1.0
Qt version : 6.3.1
WoWs version 0.11.8.0

Edition	Windows 10 Pro
Version	21H2
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

Also, not sure if related, when the updater runs and it finishes, it runs the app again ( eg in task manager ) but there is no visuals and and no active window. I have to kill it ( with TM ) and open it again.

**Comment by razaqq** [comment]
Hey thanks for the report, i will try to look into it.

Can you provide me with some logs of when this is happening (Menubar has an icon to get to the logs).
Does this happen every time without exception?
Do you have the steam or standalone version?

There is also a discord where im active, you might get a response there faster.

**Comment by DarkMukke** [comment]
Can do, I can also build my own version if you need extra debug ( CPP has been a while, I do mostly Rust now), I'll reach out on Discord

**Comment by razaqq** [comment]
Alright i will create a test version to see if that fixes it, but since you are so far the only person with this bug you need to test it for me (hop on discord if you can)

**Comment by DarkMukke** [comment]
can you friend me ? DarkMukke#1207 
Can't see you on any of the discords I am on

**Comment by DarkMukke** [comment]
I have tested the [reading-arenainfo-bug](https://github.com/razaqq/PotatoAlert/tree/reading-arenainfo-bug) branch ( or at least the artifact created by CI ) and I can confirm that fixed the problem.

**Comment by razaqq** [comment]
Closing this then
