### ISSUE TITLE
Unable to move the windows after rewindow the application

### ISSUE THREAD

**Issue by ParaTrix** [razaqq/PotatoAlert#39]
OS: Window 10 21H2
App: Version 3.1.0

After click X button to hide the window then rewindow it by double click the icon in taskbar, i notice that window is unable to move around anymore, had to quit the app and restart it.

All other functions are working perfect, just unable to move it though the top of the window.

**Comment by razaqq** [comment]
fixed in #d84c544, next update will include it

Many thanks for reporting
