### ISSUE TITLE
WOWS.WW.PRODUCTION is no longer in Registry

### ISSUE THREAD

**Issue by HenryQuan** [razaqq/PotatoAlert#44]
It seems that `SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WOWS.WW.PRODUCTION` is no longer found in the Registry. It is using something like `1527964767` instead. I can confirm that this is happening on my other PC. The number of the PT server is `2376840996`.

**Comment by razaqq** [comment]
I will take a look

**Comment by HenryQuan** [comment]
Thank you. Another developer told me the number is random, not fixed. I am not sure if this is the case. He is looping through all the folders to find the publisher name to be wargaming.

**Comment by razaqq** [comment]
yeah mine is other than yours aswell, so seems to be random
yeah can loop over all keys and look for `DisplayName == 'World_Of_Warships' && Publisher == 'Wargaming.net'`

**Comment by razaqq** [comment]
should be fixed in 183c1b6ff62940843160bb98d1bab61a23d0aa71
