### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by jensjcs** [razaqq/PotatoAlert#51]
Hello, since today i get a "connection timeout". until yesterday it worked fine and without any problems.

maybe you can where the problem is. i added also the log file.

greetings
jens

[PotatoAlert.log](https://github.com/user-attachments/files/16054336/PotatoAlert.log)

**Comment by razaqq** [comment]
There is an announcement in discord that explains it. The server is temporarily down, but it should be back up soon.
