### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by goofy7264** [razaqq/PotatoAlert#52]
Getting Red Bang : Server Error when loading into match.  Not sure what is causing it and it happens most of the time, but not all the time.

![error-potato](https://github.com/user-attachments/assets/c153fd83-f514-4e8b-8dc7-397ed70afa42)

**Comment by razaqq** [comment]
yeah i know, the NA api has been constanly timing out the last couple of days.
there is nothing i can do, you can thank wargaming for this.

**Comment by goofy7264** [comment]
maybe, as a thought, add a better error message saying API not Available, for example so everyone knows where the issue is?  Just a suggestion of course.

**Comment by razaqq** [comment]
I will see what i can do
