### ISSUE TITLE
Potato Alert

### ISSUE THREAD

**Issue by mca61** [razaqq/PotatoAlert#54]
Since the last update a few days ago, I have noticed potato alert having issues.
- error displayed as "WG API Error"
- not showing karma for all players, instead giving a "0"
I have raised this issue with Aslan on aslan.com and he recommended I convey this to you.

![PA_error](https://github.com/user-attachments/assets/6132f649-6a6f-4a86-bdf4-a6e868d2b737)

**Comment by razaqq** [comment]
same issue as https://github.com/razaqq/PotatoAlert/issues/52
i have explained this in great detail in discord, nothing i can do

**Comment by mca61** [comment]
is the karma not showing also related to the NA api has been constanly timing out the last couple of days?

**Comment by razaqq** [comment]
yes
