### ISSUE TITLE
Window does not open properly.

### ISSUE THREAD

**Issue by Mareeeeek** [razaqq/PotatoAlert#55]
When turning off a Secondary Monitor on which Potato Alert was running, it does not open properly in the next Session.
For Example, I play on a Laptop with a Secondary Monitor at Home and run Potato Alert on the Secondary Monitor. But if I End the Session and want to run Potato Alert elsewhere with the Main Monitor only, it does not open up properly. Only a White Window Appears that I can't maximize. 
![Screenshot 2024-09-18 101113](https://github.com/user-attachments/assets/bc068729-408d-48a5-a089-6e2a5b691ff3)

**Comment by razaqq** [comment]
Can you send me the logs from `%localappdata%\PotatoAlert\PotatoAlert.log`?

**Comment by Mareeeeek** [comment]
[PotatoAlert.log](https://github.com/user-attachments/files/17185051/PotatoAlert.log)
There you go

**Comment by razaqq** [comment]
Fix in 96f7baf4ed42d4cfc4ad7155a64bce508b23dc2a
