### ISSUE TITLE
do not lunching at all..

### ISSUE THREAD

**Issue by Mikeldj77** [razaqq/PotatoAlert#56]
Hi ,
since 2 updates, potato do not luch at all. i can see it for 2 seconds in task but potato windows never appear.
all was fine with previous version so i do not know what to do.
i try to install it with Aslain gamepack or with zip standalon or with windows installer but the result is always the same...

if you have an idea...

ty !

**Comment by razaqq** [comment]
Do you have the latest microsoft visual c++ redistributable installed? https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Mikeldj77** [comment]
i will check that...ty
i will feedback
