### ISSUE TITLE
Potato Alert Not Opening Despite Multiple Attempts 

### ISSUE THREAD

**Issue by B-doe** [razaqq/PotatoAlert#57]
Hi,

The Potato Alert app isn't starting at all on my Windows 11. I've tried using the update tool, reinstalling it multiple times, running as admin, and I've tried compatibility testing with no success.  The program simply doesn't open and it cannot be found in the task manager. 

I love using Potato Alert, I would really appreciate your support. I noticed you requested logs in response to another issue, please see attached.

![potato](https://github.com/user-attachments/assets/da30e623-004d-490a-9962-0bc3dbac13e4)

**Comment by razaqq** [comment]
Do you have the latest microsoft visual c++ redistributable installed? [aka.ms/vs/17/release/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by B-doe** [comment]
It opened, thank you so much for the prompt response and the superb program you've created! I can't game without it :)

**Comment by razaqq** [comment]
No problem, glad you like it
