### ISSUE TITLE
Not A WoWs Directory

### ISSUE THREAD

**Issue by ElmirKG** [razaqq/PotatoAlert#58]
Hello! Is the Ru region supported? Writes "Not A WoWs Directory". I am attaching a screenshot of the game folder and the potato alert settings
![2024-09-30_210028](https://github.com/user-attachments/assets/0d9898cb-a78e-48e1-9da4-9515763d9134)
![2024-09-30_205712](https://github.com/user-attachments/assets/d9ef123c-2515-4835-98fa-6ca8059f80ea)

**Comment by razaqq** [comment]
No the RU region is no longer supported since lesta took over, the games have become too different for me to support
