### ISSUE TITLE
 Does this mod still work properly?

### ISSUE THREAD

**Issue by Godlike-Yu** [razaqq/PotatoAlert#60]
I got
“Server responded with error to submit: Error transferring <redacted> - server replied: Bad Request”
every time. : (

**Comment by Godlike-Yu** [comment]
> what region are you playing on? what version of PA are you using? and can you send me a replay of one of these games?

sure.game server is "North America". is PA vesion mean potatoalert version? i think it is 3.1.24.and a attach
[20241026_110902_PASB111-Maine_16_OC_bees_to_honey.zip](https://github.com/user-attachments/files/17529418/20241026_110902_PASB111-Maine_16_OC_bees_to_honey.zip)

**Comment by razaqq** [comment]
Hmm this replay loads fine for me and 3.1.24 is the latest version.
Do you have discord? Would help if you would join the PA discord as its much faster to respond there https://discord.gg/Ut8t8PA
Can you send me screenshots of your settings and game directory settings like this?
![24-10-26_10-10-18_ozKsnm7x](https://github.com/user-attachments/assets/a9d478f2-2099-42df-85e4-5fb6b5bfd6a5)

**Comment by razaqq** [comment]
fixed
