### ISSUE TITLE
Need help. Dont know how to start it

### ISSUE THREAD

**Issue by Jvooch** [razaqq/PotatoAlert#61]
I have downloaded the latest version. unzipped the folder and i do not know where to go from there.

**Comment by razaqq** [comment]
Start PotatoAlert.exe

**Comment by Jvooch** [comment]
i do not see a potatoalert.exe

**Comment by razaqq** [comment]
Then you didnt unzip it

**Comment by Jvooch** [comment]
that worked thanks
