### ISSUE TITLE
My PA is not working..

### ISSUE THREAD

**Issue by HotTager** [razaqq/PotatoAlert#62]
![image](https://github.com/user-attachments/assets/4bdeaa26-8828-4efc-8829-bb7a860162e2)
My PA is not working. I can only see my own ship.

Please help?

**Comment by razaqq** [comment]
what mode is this? some sort of pve mode?

**Comment by HotTager** [comment]
It’s in Ranked

**Comment by razaqq** [comment]
Send me the replay please

**Comment by HotTager** [comment]
[20241105_211632_PVSB018-Ipiranga_04_Archipelago.zip](https://github.com/user-attachments/files/17642173/20241105_211632_PVSB018-Ipiranga_04_Archipelago.zip)
![image](https://github.com/user-attachments/assets/97812fbd-37f5-4d73-adb6-104f4766a864)

**Comment by HotTager** [comment]
![image](https://github.com/user-attachments/assets/3987fd2f-af89-4897-9443-2e95ea3e7563)
I checked my log, it was working fine on 24/10/2024 around 12.40pm.
After I restarted the game, at 24/10/2024 at 15.09, it's not working anymore..
![image](https://github.com/user-attachments/assets/d5c45ac1-6e84-4a43-9bf4-4d1b8b468dc5)
![image](https://github.com/user-attachments/assets/3415c568-6e33-4a82-9998-918745ce3188)

**Comment by HotTager** [comment]
![image](https://github.com/user-attachments/assets/db78e1ef-f125-4e31-995d-43fa41f5e8d0)
This is the logfile. No updates was made during the time when it was working to not working..

**Comment by HotTager** [comment]
ok, let me try to run without mods

**Comment by HotTager** [comment]
OK! It's sorted!! thank you so much!

**Comment by razaqq** [comment]
np
